-- MySQL Script generated by MySQL Workbench
-- Fri Jan  6 10:13:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `MATIERE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MATIERE` ;

CREATE TABLE IF NOT EXISTS `MATIERE` (
  `idMATIERE` INT NOT NULL,
  `intitule` VARCHAR(45) NULL,
  PRIMARY KEY (`idMATIERE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENSEIGNANT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ENSEIGNANT` ;

CREATE TABLE IF NOT EXISTS `ENSEIGNANT` (
  `idENSEIGNANT` INT NOT NULL,
  `nomEnseignant` VARCHAR(45) NULL,
  `prenomEnseignant` VARCHAR(45) NULL,
  `MATIERE_idMATIERE` INT NOT NULL,
  PRIMARY KEY (`idENSEIGNANT`, `MATIERE_idMATIERE`),
  INDEX `fk_ENSEIGNANT_MATIERE_idx` (`MATIERE_idMATIERE` ASC) VISIBLE,
  CONSTRAINT `fk_ENSEIGNANT_MATIERE`
    FOREIGN KEY (`MATIERE_idMATIERE`)
    REFERENCES `MATIERE` (`idMATIERE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
