-- MySQL Script generated by MySQL Workbench
-- Fri Jan  6 10:09:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maillé
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `EMISSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMISSION` ;

CREATE TABLE IF NOT EXISTS `EMISSION` (
  `idEMISSION` INT NOT NULL,
  `nomEmission` VARCHAR(45) NULL,
  PRIMARY KEY (`idEMISSION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANIMATEUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ANIMATEUR` ;

CREATE TABLE IF NOT EXISTS `ANIMATEUR` (
  `idANIMATEUR` INT NOT NULL,
  `nomAnimateur` VARCHAR(45) NULL,
  `prenomAnimateur` VARCHAR(45) NULL,
  PRIMARY KEY (`idANIMATEUR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Animer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Animer` ;

CREATE TABLE IF NOT EXISTS `Animer` (
  `EMISSION_idEMISSION` INT NULL,
  `ANIMATEUR_idANIMATEUR` INT NULL,
  PRIMARY KEY (`EMISSION_idEMISSION`, `ANIMATEUR_idANIMATEUR`),
  INDEX `fk_EMISSION_has_ANIMATEUR_ANIMATEUR1_idx` (`ANIMATEUR_idANIMATEUR` ASC) VISIBLE,
  INDEX `fk_EMISSION_has_ANIMATEUR_EMISSION_idx` (`EMISSION_idEMISSION` ASC) VISIBLE,
  CONSTRAINT `fk_EMISSION_has_ANIMATEUR_EMISSION`
    FOREIGN KEY (`EMISSION_idEMISSION`)
    REFERENCES `EMISSION` (`idEMISSION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMISSION_has_ANIMATEUR_ANIMATEUR1`
    FOREIGN KEY (`ANIMATEUR_idANIMATEUR`)
    REFERENCES `ANIMATEUR` (`idANIMATEUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
